/* Flattens the design-system token files into one styles.css so the browser
   makes a single blocking CSS request instead of a 3-level @import waterfall
   (styles.css → tokens/*.css → Google Fonts).
   - Source of truth stays in public/tokens/*.css — edit those, then run:
       node scripts/flatten-css.mjs
   - The Google Fonts @import is intentionally dropped: every page loads the
     fonts via a <link> in its <head> (parallel, non-cascading). */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUB = resolve(__dirname, '../public');
const ORDER = ['fonts', 'colors', 'typography', 'spacing', 'effects', 'base'];

let out = `/* ════════════════════════════════════════════════════════════════════════
   Chic Nail & Head Spa — Design System (flattened build)
   GENERATED by scripts/flatten-css.mjs — do not edit by hand.
   Edit public/tokens/*.css and re-run: node scripts/flatten-css.mjs
   Google Fonts load via a <link> in each page's <head>, not @import.
   ════════════════════════════════════════════════════════════════════════ */
`;

for (const name of ORDER) {
  let css = await readFile(resolve(PUB, 'tokens', `${name}.css`), 'utf8');
  css = css.replace(/@import[^;]+;\s*/g, ''); // fonts load from the HTML head
  out += `\n/* ── tokens/${name}.css ${'─'.repeat(Math.max(4, 56 - name.length))} */\n${css.trim()}\n`;
}

await writeFile(resolve(PUB, 'styles.css'), out);
console.log(`styles.css flattened (${out.length} bytes) from ${ORDER.length} token files`);
